#pragma config(Motor,  port1,           Motor1,        tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           Motor2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           Motor3,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           driveFrontLeft, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           driveFrontRight, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           driveBackLeft, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           driveBackRight, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           Motor8,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Motor4,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          Motor5,        tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{



		if(vexRT[Btn5U] == 1)
		{

			motor[Motor5] = 127;
			motor[Motor1] = 127;
			motor[Motor2] = 127;
			motor[Motor3] = 127;
			motor[Motor4] = 127;
			motor[Motor8] = 127;
		}

		if(vexRT[Btn5D] == 1)
		{
			motor[Motor5] = 0;
			motor[Motor1] = 0;
			motor[Motor2] = 0;
			motor[Motor3] = 0;
			motor[Motor4] = 0;
			motor[Motor8] = 0;
		}

		motor[driveFrontRight] = vexRT[Ch1] + vexRT[Ch4] - vexRT[Ch2];
		motor[driveFrontLeft] = vexRT[Ch1] - vexRT[Ch4];
		motor[driveBackRight] = vexRT[Ch1] - vexRT[Ch4] + vexRT[Ch2];
		motor[driveBackLeft] = vexRT[Ch1] + vexRT[Ch4];

	}
}
